// Migration Configuration
// Generated by setup script

module.exports = {
  local: {
    host: 'logisticsdb',
    port: 5432,
    database: 'logisticsdb',
    user: 'postgres',
    password: 'admin123'
  },
  neon: {
    host: ''postgresql://neondb_owner:npg_iWdBt3xb2PRq@ep-green-rice-adtvyi8t-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'',
    port: 5432,
    database: 'logisticsdb',
    user: 'neondb_owner',
    password: 'npg_iWdBt3xb2PRq',
    ssl: { rejectUnauthorized: false }
  }
};
